name: Update translations in main
on:
  push:
    branches:
      - pontoon

jobs:
  rebase:

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "New Pontoon translations"
          pr_label: "Area: Translation"
